import { User, ClassSession, AttendanceRecord, Assignment, QAQuestion, MicroTask, NotificationItem } from './types';

export const INITIAL_USER: User = {
  id: 'usr-123',
  studentId: '65040123',
  fullName: 'Nadia Srikanya',
  email: 'nadia.sri@university.ac.th',
  faculty: 'คณะวิทยาการสารสนเทศ (Computer Science)',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuALURAKLvqJS7psfy3Q8I5i_201j2Tdy2w8_a02aCAeM5JdUq9RbsOCmK8M2Ce7WG0p9GfirrrCv9FpmXiOkMDPlEkhG35-hH2zmIJdDutaoYoY_2xAIZe9u6Y9nJWFrqbPfuLzR1adc7beiIsQkOtHCldioF1AIoynwqTxah-MRtVwtlwbN7PeOUs0m-g2To2pdQD1qAVVCnu33ODRvBYSTNPhWPlL_BWq4oRnMuTqcwgNM6mQR5dSlg',
  level: 4,
  totalXp: 850,
  maxXp: 1000,
  grade: 'A Grade',
  rankTitle: 'พลทหาร',
  gpa: 3.82,
  attendanceRate: 85,
  completedTasks: 25,
  totalTasks: 28,
};

export const INITIAL_CLASSES: ClassSession[] = [
  {
    id: 'cls-1',
    code: 'CS101',
    title: 'Intro to AI',
    instructor: 'อ. ดร. สมชาย ใจดี',
    time: '09:00 - 12:00',
    location: 'Room 402',
    status: 'กำลังเรียน',
    day: 'วันนี้ (จันทร์)',
  },
  {
    id: 'cls-2',
    code: 'CS102',
    title: 'Data Structures',
    instructor: 'ผศ.ดร. ณัฐพล มั่นคง',
    time: '13:00 - 16:00',
    location: 'Lab 305',
    status: 'ถัดไป',
    day: 'วันนี้ (จันทร์)',
  },
  {
    id: 'cls-3',
    code: 'INT201',
    title: 'Web Technologies',
    instructor: 'ดร. กรกช รัตนพงษ์',
    time: '09:00 - 12:00',
    location: 'Lab 201',
    status: 'ถัดไป',
    day: 'อังคาร',
  },
  {
    id: 'cls-4',
    code: 'INT202',
    title: 'Database Systems',
    instructor: 'อ. วรรณภา สุขสำราญ',
    time: '13:00 - 16:00',
    location: 'Room 501',
    status: 'ถัดไป',
    day: 'พุธ',
  },
  {
    id: 'cls-5',
    code: 'GEN111',
    title: 'Man & Ethics',
    instructor: 'ผศ.ดร. อัมพร พงษ์สวัสดิ์',
    time: '09:00 - 12:00',
    location: 'Auditorium 1',
    status: 'ถัดไป',
    day: 'พฤหัสบดี',
  },
];

export const INITIAL_ATTENDANCE_HISTORY: AttendanceRecord[] = [
  {
    id: 'att-1',
    courseCode: 'INT201',
    courseName: 'Web Technologies',
    date: '12 ก.ย. 2023',
    time: '09:15 น.',
    status: 'เข้าเรียน',
  },
  {
    id: 'att-2',
    courseCode: 'INT202',
    courseName: 'Database Sys',
    date: '10 ก.ย. 2023',
    time: '13:45 น.',
    status: 'สาย',
    lateMinutes: 15,
  },
  {
    id: 'att-3',
    courseCode: 'GEN111',
    courseName: 'Man & Ethics',
    date: '08 ก.ย. 2023',
    time: '09:00 น.',
    status: 'ขาดเรียน',
  },
  {
    id: 'att-4',
    courseCode: 'CS101',
    courseName: 'Intro to AI',
    date: '05 ก.ย. 2023',
    time: '09:05 น.',
    status: 'เข้าเรียน',
  },
  {
    id: 'att-5',
    courseCode: 'CS102',
    courseName: 'Data Structures',
    date: '01 ก.ย. 2023',
    time: '13:00 น.',
    status: 'เข้าเรียน',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-1',
    title: 'ส่งรายงานโปรเจกต์กลุ่ม AI',
    courseCode: 'CS101',
    courseName: 'Intro to AI',
    dueDate: 'พรุ่งนี้ 23:59 น.',
    dueTimestampText: 'พรุ่งนี้ 23:59 น.',
    isUrgent: true,
    status: 'ยังไม่ส่ง',
  },
  {
    id: 'asg-2',
    title: 'แบบฝึกหัดเรื่อง Data Structures',
    courseCode: 'CS102',
    courseName: 'CS102 Data Struct',
    dueDate: 'ศุกร์ที่ 15 ก.ย. 23:59 น.',
    dueTimestampText: 'ศุกร์ที่ 15 ก.ย. 23:59 น.',
    status: 'ยังไม่ส่ง',
  },
  {
    id: 'asg-3',
    title: 'Micro-Reflection: UX Ethics',
    courseCode: 'INT201',
    courseName: 'Web Technologies',
    dueDate: 'ส่งแล้ว 2 วันก่อน',
    dueTimestampText: 'ส่งแล้ว 2 วันก่อน',
    score: '10/10',
    maxScore: 10,
    status: 'ตรวจแล้ว',
    teacherFeedback: 'วิเคราะห์ได้ตรงประเด็นมากครับ เห็นภาพชัดเจนถึงผลกระทบต่อผู้ใช้งานจริง...',
  },
  {
    id: 'asg-4',
    title: 'Quiz 3: Normalization',
    courseCode: 'INT202',
    courseName: 'Database Systems',
    dueDate: 'ส่งแล้ว 4 ชม. ก่อน',
    dueTimestampText: 'ส่งแล้ว 4 ชม. ก่อน',
    status: 'รอตรวจ',
  },
];

export const INITIAL_QUESTIONS: QAQuestion[] = [
  {
    id: 1,
    text: 'อาจารย์ครับ โปรเจกต์ท้ายเทอมต้องทำเป็นกลุ่มหรือเดี่ยวครับ? แล้วจับกลุ่มข้ามเซคได้ไหม?',
    timeAgo: '2 นาทีที่แล้ว',
    votes: 42,
    userVoted: false,
    createdAt: new Date(Date.now() - 120000),
  },
  {
    id: 2,
    text: 'สไลด์บทที่ 4 หน้า 12 ที่เป็นสูตรคำนวณ ผมยังไม่ค่อยเข้าใจที่มาของตัวแปร C ครับ ช่วยอธิบายเพิ่มได้ไหมครับ',
    timeAgo: '15 นาทีที่แล้ว',
    votes: 18,
    userVoted: false,
    createdAt: new Date(Date.now() - 900000),
  },
  {
    id: 3,
    text: 'มีไฟล์บันทึกวิดีโอย้อนหลังของคาบวิชา Data Structures ย้อนหลังไหมครับ?',
    timeAgo: '45 นาทีที่แล้ว',
    votes: 9,
    userVoted: false,
    createdAt: new Date(Date.now() - 2700000),
  },
];

export const INITIAL_MICRO_TASK: MicroTask = {
  id: 'mt-04',
  title: 'งานย่อยประจำวัน (Micro-Task 04)',
  description: 'ส่งลิงก์สรุปบทความวิจัยที่คุณได้อ่านในวันนี้',
  dueDate: 'วันนี้ 23:59',
  isSubmitted: false,
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'เช็กชื่อเข้าเรียนสำเร็จ',
    message: 'คุณได้บันทึกเวลาเรียนวิชา CS101 Intro to AI เรียบร้อยแล้ว (09:03 น.)',
    time: '10 นาทีที่แล้ว',
    read: false,
    type: 'class',
  },
  {
    id: 'notif-2',
    title: 'ประกาศผลคะแนน',
    message: 'อาจารย์ได้ตรวจ Micro-Reflection: UX Ethics แล้ว ได้คะแนน 10/10!',
    time: '2 วันก่อน',
    read: true,
    type: 'grade',
  },
  {
    id: 'notif-3',
    title: 'แจ้งเตือนกำหนดส่งงาน',
    message: 'งาน "ส่งรายงานโปรเจกต์กลุ่ม AI" ครบกำหนดส่งพรุ่งนี้ 23:59 น.',
    time: '3 วันก่อน',
    read: true,
    type: 'task',
  },
];
